local augroup = vim.api.nvim_command

augroup([[augroup Scrollbar]])
augroup([[autocmd!]])
augroup([[autocmd CursorMoved,VimResized,QuitPre * silent! lua require('scrollbar').show()]])
augroup([[autocmd WinEnter,FocusGained,BufEnter * silent! lua require('scrollbar').show()]])
augroup([[autocmd WinLeave,FocusLost,BufLeave * silent! lua require('scrollbar').clear()]])
augroup([[augroup END]])

augroup([[augroup Theme]])
augroup([[autocmd!]])
augroup([[autocmd VimEnter * hi Normal guibg=NONE]])
augroup([[autocmd VimEnter * hi Cursor guibg=NONE]])
augroup([[autocmd VimEnter * hi CursorLine guibg=#3B4252]])
augroup([[autocmd VimEnter * hi CursorLineNr guibg=NONE]])
augroup([[autocmd VimEnter * hi ColorColumn guibg=NONE]])
augroup([[autocmd VimEnter * hi LineNr guibg=NONE]])
augroup([[autocmd VimEnter * hi EndOfBuffer guibg=#282C34 guifg=#282C34]])
augroup([[autocmd VimEnter * hi VertSplit guibg=NONE guifg=#3e4451]])
augroup([[autocmd VimEnter * hi Whitespace guifg=#949494]])
augroup([[autocmd VimEnter * hi StatusLineNC gui=underline guibg=NONE guifg=#3e4451]])
augroup([[autocmd VimEnter * hi Pmenusel guibg=#85dc85]])
augroup([[autocmd VimEnter * hi Pmenu guibg=#353b45]])
augroup([[augroup END]])

augroup([[augroup Terminal]])
augroup([[autocmd!]])
augroup([[autocmd TermOpen * setlocal nonumber]])
augroup([[autocmd TermOpen * setlocal norelativenumber]])
augroup([[augroup END]])

augroup([[augroup Git]])
augroup([[autocmd!]])
augroup([[autocmd VimEnter * hi DiffAdd guifg = #81A1C1 guibg = none]])
augroup([[autocmd VimEnter * hi DiffChange guifg = #3A3E44 guibg = none]])
augroup([[autocmd VimEnter * hi DiffModified guifg = #81A1C1 guibg = none]])
augroup([[augroup END]])

augroup([[augroup Tree]])
augroup([[autocmd!]])
augroup([[autocmd VimEnter * hi NvimTreeFolderIcon guifg = #61afef]])
augroup([[autocmd VimEnter * hi NvimTreeFolderName guifg = #61afef]])
augroup([[autocmd VimEnter * hi NvimTreeIndentMarker guifg=#383c44]])
augroup([[augroup END]])

augroup([[augroup Telescope]])
augroup([[autocmd!]])
augroup([[autocmd VimEnter * hi TelescopeBorder   guifg=#525865]])
augroup([[autocmd VimEnter * hi TelescopePromptBorder   guifg=#525865]])
augroup([[autocmd VimEnter * hi TelescopeResultsBorder  guifg=#525865]])
augroup([[autocmd VimEnter * hi TelescopePreviewBorder  guifg=#525865]])
augroup([[augroup END]])

augroup([[augroup VIMRC]])
augroup([[autocmd!]])
augroup([[autocmd InsertEnter * set nocul]])
augroup([[autocmd InsertLeave * set cul]])
augroup([[autocmd VimEnter * set formatoptions-=cro]])
augroup([[augroup END]])

augroup([[augroup Format]])
augroup([[autocmd!]])
augroup([[autocmd BufWritePre * undojoin | Neoformat]])
augroup([[augroup END]])

augroup([[augroup Vertical]])
augroup([[autocmd!]])
augroup([[autocmd! BufEnter * if &ft ==# 'help' | wincmd L | endif]])
augroup([[augroup END]])

augroup([[augroup Blameline]])
augroup([[autocmd!]])
augroup([[autocmd BufEnter * EnableBlameLine]])
augroup([[augroup END]])
